server:
  port: 8080

spring:
  application:
    name: reservation-time-service

  datasource:
    url: jdbc:h2:mem:reservationdb
    driver-class-name: org.h2.Driver
    username: sa
    password:

  h2:
    console:
      enabled: true
      path: /h2-console

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.H2Dialect

  sql:
    init:
      mode: always
      platform: h2
      continue-on-error: false

logging:
  level:
    root: INFO
    com.invt.tech: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: "*"

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: method
    tagsSorter: alpha
  default-produces-media-type: application/json

info:
  title: Flexibility Reservation API
  description: REST API for downloading flexibility reservation data in CSV
  version: 1.0.0