server:
  port: 8080

spring:
  application:
    name: reservation-time-service

  datasource:
    url: jdbc:h2:mem:reservationdb
    driver-class-name: org.h2.Driver
    username: sa
    password:

  h2:
    console:
      enabled: true
      path: /h2-console

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.H2Dialect

logging:
  level:
    root: INFO
    com.invt.tech: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: "*"
