version: '3.8'

services:
  reservation-time-service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: reservation-time-service
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: default
      SPRING_H2_CONSOLE_SETTINGS_WEB_ALLOW_OTHERS: "true"
    volumes:
      - ./logs:/app/logs
    restart: unless-stopped